### ISSUE TITLE
add windows build

### ISSUE THREAD

**Issue by carlodri** [conda-forge/qpdf-feedstock#12]
win build is also blocking pikepdf builds on same platform

Issue:

<br/>
Environment (<code>conda list</code>):
<details>

```
$ conda list

```
</details>

<br/>
Details about  <code>conda</code> and system ( <code>conda info</code> ):
<details>

```
$ conda info

```
</details>

**Comment by jakirkham** [comment]
@conda-forge-admin , please re-render
